scalar Date

interface Node {
  id: ID!
}

type Viewer {
  playlist: PlayList
}

type Query {
  node(id: ID!): Node
  viewer: Viewer
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}
