language: node_js

node_js:
  - 'node'
  - '10'

sudo: true

cache:
  directories:
    - $HOME/common/node_modules
    - $HOME/server/node_modules
    - $HOME/client/node_modules

before_install:
  - sudo apt-get install -y libasound2-dev
  - npm install codecov -g

install:
  - cd common && npm install && cd -
  - cd server && npm install && cd -
  - cd client && yarn install && cd -

script:
  - cd common && bash ../scripts/ci-common.sh && cd -
  - cd client && bash ../scripts/ci-client.sh && cd -
  - cd server && bash ../scripts/ci-server.sh && cd -

after_script:
  - bash ./scripts/dist-copy.sh
  - bash ./scripts/dist-archive.sh

branches:
  only:
  - master

after_success:
  - cd common &&  bash <(curl -s https://codecov.io/bash) -cF javascript && cd -
  - cd server &&  bash <(curl -s https://codecov.io/bash) -cF javascript && cd -
  - cd client &&  bash <(curl -s https://codecov.io/bash) -cF javascript && cd -

notifications:
  email: false

