language: node_js

node_js:
  - 'node'
  - '10'

sudo: true

cache:
  directories:
    - $HOME/build/if1live/sato/common/node_modules
    - $HOME/build/if1live/sato/server/node_modules
    - $HOME/build/if1live/sato/client/node_modules

before_install:
  - sudo apt-get install -y libasound2-dev
  - yarn global add codecov
  - cd common && yarn link && cd -
  - cd server && yarn link common && cd -
  - cd client && yarn link common && cd -

install:
  - cd common && yarn install && cd -
  - cd server && yarn install && cd -
  - cd client && yarn install && cd -

script:
  - cd common && bash ../scripts/ci-common.sh && cd -
  - cd client && bash ../scripts/ci-client.sh && cd -
  - cd server && bash ../scripts/ci-server.sh && cd -

after_script:
  - bash ./scripts/dist-copy.sh
  - bash ./scripts/dist-archive.sh

branches:
  only:
  - master

after_success:
  - cd common &&  bash <(curl -s https://codecov.io/bash) -cF javascript && cd -
  - cd server &&  bash <(curl -s https://codecov.io/bash) -cF javascript && cd -
  - cd client &&  bash <(curl -s https://codecov.io/bash) -cF javascript && cd -

notifications:
  email: false

