input PlayAudioInput {
  clientMutationId: ID!
  videoId: String!
}

type PlayAudioPayload {
  clientMutationId: ID!
  ok: Boolean
}

input StopAudioInput {
  clientMutationId: ID!
}

type StopAudioPayload {
  clientMutationId: ID!
}

type Mutation {
  playAudio(input: PlayAudioInput): PlayAudioPayload
  stopAudio(input: StopAudioInput): StopAudioPayload
}
